language: ruby
rvm:
  - 2.2
before_script:
  - gem install awesome_bot
script:
  - awesome_bot README.md --allow-redirect --white-list linkedin.com,kismatic.com --allow-dupe http://creativecommons.org/licenses/by-nc/4.0/
